### ISSUE TITLE
SQLScout (SQLite Support) threw an uncaught NoClassDefFoundError.

### ISSUE THREAD

**Issue by micookie** [wangjiegulu/wangjiegulu.github.com#6]
Android Studio 2.2.1
Scout版本：2.0.6和2.0.7
破解jar文件版本一致。

1、下载到本地查看的时候报错：
文件可以成功下载，但是不能查看数据。View Table Data报错，执行SQL语句同样报错。

![BaiduShurufa_2016-11-9_10-36-0.png](https://ooo.0o0.ooo/2016/11/09/58228c0006704.png)

2、在线连接的时候报错：（可能和我的程序有关，可以先忽略）
![BaiduShurufa_2016-11-9_10-35-29.png](https://ooo.0o0.ooo/2016/11/09/58228c001d91e.png)

**Comment by micookie** [comment]
刚才试了一下2.0.4也会报同样的错误。。
。报错的同时Android Studio也会弹出一个错误。。
下面是错误内容：
```
com.intellij.ui.components.JBScrollPane$MyScrollBar cannot be cast to com.intellij.execution.console.LanguageConsoleImpl$EmptyScrollBar
java.lang.ClassCastException: com.intellij.ui.components.JBScrollPane$MyScrollBar cannot be cast to com.intellij.execution.console.LanguageConsoleImpl$EmptyScrollBar
	at com.intellij.execution.console.LanguageConsoleImpl.setHistoryScrollBarVisible(LanguageConsoleImpl.java:194)
	at com.intellij.execution.console.LanguageConsoleImpl.setConsoleEditorEnabled(LanguageConsoleImpl.java:185)
	at com.idescout.sqlite.console.DatabaseConsole.<init>(Unknown Source)
	at com.idescout.sqlite.console.DatabaseConsole.getInstance(Unknown Source)
	at com.idescout.sqlite.service.DatabaseAccess$StatementExecutionRequest.getConsole(Unknown Source)
	at com.idescout.sqlite.service.d.run(Unknown Source)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2440)
	at com.idescout.sqlite.service.DatabaseAccess.a(Unknown Source)
	at com.idescout.sqlite.service.DatabaseAccess.execute(Unknown Source)
	at com.idescout.sqlite.actions.AbstractDisplayTableDataAction.actionPerformed(Unknown Source)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:191)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:312)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:282)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:110)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:513)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:45)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:533)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by junerver** [comment]
遇到了相同的问题!

**Comment by dengniSLM** [comment]
遇到了相同的问题!

**Comment by sunflower-zyb** [comment]
遇到了相同的问题!

**Comment by my29** [comment]
遇到了相同的问题!

**Comment by wangzhe56888** [comment]
我昨天还用着没问题，今天就出现了这样的问题，请问楼主解决了吗？（MAC，android studio 2.2）

**Comment by BlackJia** [comment]
#同样的问题#**Plugin Error   SQLScout (SQLite Support) threw an uncaught NoClassDefFoundError**

**Comment by BlackJia** [comment]
NoClassDefFoundError: com/idescout/sqlite/console/D

**Comment by micookie** [comment]
@BlackJia 没有解决，我的一直是这样的

**Comment by wenjiang** [comment]
今天我在Mac上也遇到了同样的问题，Android Studio 2.2

**Comment by zzhhz** [comment]
SQLScout (SQLite Support) threw an uncaught NoClassDefFoundError.  
View Table Data报错, 同样的错误，请问应该怎么解决

**Comment by jiangecho** [comment]
请问用的java 反编译工具是什么？

**Comment by zzhhz** [comment]
没用反编译工具啊，直接将SQLScout.jar文件替换的，但是一替换就出现这个问题了

**Comment by zzhhz** [comment]
@jiangecho 你知道这个问题怎么解决吗？

**Comment by jiangecho** [comment]
@zzhhz 不好意思，我也没解决，我想反编译下，但发现我用的jbe和rej这两个反编译工具，都不能反编译那个class文件。

**Comment by zzhhz** [comment]
@wangjiegulu 这个问题应该怎么解决啊？

**Comment by wangjiegulu** [comment]
@zzhhz 不好意思，刚测试这个破解版目前已经无效了，需要重新破解，我会抽时间继续跟进。用的反编译工具是Luyten

**Comment by zzhhz** [comment]
好的，今天上午刚刚解决了这个问题

**Comment by zzhhz** [comment]
不知道，文件怎么提交给你

**Comment by wangjiegulu** [comment]
问题已经解决：
https://github.com/wangjiegulu/wangjiegulu.github.com/tree/master/file/SQLScout/2.0.7
把`SQLScout.jar`和`SQLScout_console_part.jar`两个文件都拷贝过去即可

**Comment by zzhhz** [comment]
1

**Comment by jiangecho** [comment]
@wangjiegulu 谢谢，请问你用什么工具来修改class文件？

**Comment by wangjiegulu** [comment]
@jiangecho `javassist`
